//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class correspodence_tbl
    {
        public int correspodence_id { get; set; }
        public int group_id { get; set; }
        public System.DateTime date { get; set; }
        public string sending_id { get; set; }
        public string contents { get; set; }
        public string addressee { get; set; }
    
        public virtual group_tbl group_tbl { get; set; }
        public virtual person_tbl person_tbl { get; set; }
    }
}
