//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class participation_tbl
    {
        public int participation_id { get; set; }
        public Nullable<int> member_group_id { get; set; }
        public string aproval { get; set; }
        public string reminder { get; set; }
        public string timing_reminder { get; set; }
        public string actually_participation { get; set; }
        public string person_id { get; set; }
        public int meeting_id { get; set; }
    
        public virtual meeting_tbl meeting_tbl { get; set; }
        public virtual person_tbl person_tbl { get; set; }
    }
}
