//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_group_tbl
    {
        public int member_group_id { get; set; }
        public string person_id { get; set; }
        public int group_id { get; set; }
        public Nullable<System.DateTime> joining_date { get; set; }
        public Nullable<int> member_status { get; set; }
    
        public virtual group_tbl group_tbl { get; set; }
        public virtual person_tbl person_tbl { get; set; }
    }
}
