//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class groupDBEntities : DbContext
    {
        public groupDBEntities()
            : base("name=groupDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<correspodence_tbl> correspodence_tbl { get; set; }
        public virtual DbSet<group_tbl> group_tbl { get; set; }
        public virtual DbSet<meeting_tbl> meeting_tbl { get; set; }
        public virtual DbSet<member_group_tbl> member_group_tbl { get; set; }
        public virtual DbSet<participation_tbl> participation_tbl { get; set; }
        public virtual DbSet<person_tbl> person_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
